/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportSimIdRouteImport } from './routes/report.$simId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSimIdRoute = ReportSimIdRouteImport.update({
  id: '/report/$simId',
  path: '/report/$simId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/practice': typeof PracticeRoute
  '/settings': typeof SettingsRoute
  '/report/$simId': typeof ReportSimIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/practice': typeof PracticeRoute
  '/settings': typeof SettingsRoute
  '/report/$simId': typeof ReportSimIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/practice': typeof PracticeRoute
  '/settings': typeof SettingsRoute
  '/report/$simId': typeof ReportSimIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/history' | '/practice' | '/settings' | '/report/$simId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/history' | '/practice' | '/settings' | '/report/$simId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/history'
    | '/practice'
    | '/settings'
    | '/report/$simId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  PracticeRoute: typeof PracticeRoute
  SettingsRoute: typeof SettingsRoute
  ReportSimIdRoute: typeof ReportSimIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$simId': {
      id: '/report/$simId'
      path: '/report/$simId'
      fullPath: '/report/$simId'
      preLoaderRoute: typeof ReportSimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  PracticeRoute: PracticeRoute,
  SettingsRoute: SettingsRoute,
  ReportSimIdRoute: ReportSimIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
